changelog.md, docs/forms.md, lib/forms.js, lib/generate-form-url.js, lib/pre-fill-data.js, lib/prefill-data.js, package-lock.json, types.js
store in S3 using creds from API
=> ON-1589 # Update OneBlink SDK to allow passing pre-fill form data and

CHANGELOG.md, docs/form-elements/camera.md, docs/form-elements/compliance.md, docs/form-elements/draw.md, docs/form-elements/files.md, docs/form-elements/location.md, docs/form-elements/radio.md, docs/forms.md, package-lock.json, src/classes/Forms.ts, src/lib/forms-schema.ts
=> ON-11659 # Added storageType to compliance form element

package-lock.json, package.json, src/classes/Jobs.ts, src/lib/forms-schema/common.ts, src/lib/forms-schema/element-schema.ts, src/lib/forms-schema/elements/DateElement.ts, src/lib/forms-schema/elements/FileElement.ts, src/lib/forms-schema/elements/FilesElement.ts, src/lib/forms-schema/elements/HeadingElement.ts, src/lib/forms-schema/elements/NumberElement.ts, src/lib/forms-schema/elements/RepeatableSetElement.ts, src/lib/forms-schema/elements/TextElement.ts, src/lib/forms-schema/elements/TimeElement.ts, src/lib/forms-schema/index.ts, src/lib/forms-schema/property-schemas.ts, src/lib/forms-validation.ts, tests/forms-schema.test.ts, tests/jobs.test.ts
=> ON-12468 # Added regex pattern validation

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts, src/lib/forms-validation/index.ts, tests/forms-schema/forms-schema.test.ts
=> ON-24710 # Added approvalConfiguration to Form

src/classes/Forms.ts, src/lib/retrieve-submission-data.ts
Need this incase the policy used in the API that generates credentials changes to allow determining if the S3 object exists
=> ON-37205 # Cater for NoSuchKey error

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts
Types will be updated after it has been merged.
=> ON-39505 # Added `includeCalendarBookingInPdf` to event validation for PDF

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/AbnElement.ts, src/lib/forms-schema/elements/AutocompleteElement.ts, src/lib/forms-schema/elements/BarcodeElement.ts, src/lib/forms-schema/elements/BsbElement.ts, src/lib/forms-schema/elements/CheckboxElement.ts, src/lib/forms-schema/elements/CivicaNameRecordElement.ts, src/lib/forms-schema/elements/CivicaStreetNameElement.ts, src/lib/forms-schema/elements/ComplianceElement.ts, src/lib/forms-schema/elements/DateElement.ts, src/lib/forms-schema/elements/EmailElement.ts, src/lib/forms-schema/elements/FreshdeskDependentFieldElement.ts, src/lib/forms-schema/elements/GeoscapeElement.ts, src/lib/forms-schema/elements/GoogleAddressElement.ts, src/lib/forms-schema/elements/LiquorLicenceElement.ts, src/lib/forms-schema/elements/NumberElement.ts, src/lib/forms-schema/elements/PhoneElement.ts, src/lib/forms-schema/elements/PointElement.ts, src/lib/forms-schema/elements/RadioElement.ts, src/lib/forms-schema/elements/SelectElement.ts, src/lib/forms-schema/elements/TextElement.ts, src/lib/forms-schema/elements/TimeElement.ts, src/lib/forms-schema/index.ts, src/lib/forms-schema/property-schemas.ts
=> ON-43435 # Added `autocompleteAttributes` to FormElement

package-lock.json, src/lib/forms-schema/elements/CheckboxElement.ts, src/lib/forms-schema/elements/CivicaNameRecordElement.ts, src/lib/forms-schema/elements/FreshdeskDependentFieldElement.ts, src/lib/forms-schema/elements/RadioElement.ts
=> ON-43572 # Removed autocomplete validation from certain elements

DOCUMENTATION.md, src/classes/Approvals.ts, src/classes/DataManager.ts, src/classes/Forms.ts, src/classes/PDF.ts
=> ON-43625 # Added docs for submission data developer keys

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema.test.ts
=> ON-43904 # `enableSubmission` to Form schema

package-lock.json
=> ON-44227 # Updated types

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts
Types still needs to be updated and changelog will need to be updated too.
- When reviewing tests, …
=> ON-44405 # Added properties to externalIdGeneration

src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema.test.ts
=> ON-44520 # Only allowed 1 sequential number per receipt component config

CHANGELOG.md, src/classes/FormsApps.ts
=> ON-44639 # Removed FormsApps.updateStyles()

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts, src/lib/forms-validation/validate-form-events.ts, tests/forms-schema/forms-schema-form-events.test.ts, tests/forms-schema/forms-schema.test.ts
=> ON-42788 # Added NYLAS form scheduling workflow event

package-lock.json, package.json
=> ON-44866 # Bumped @oneblink/sdk-core

package-lock.json, package.json, src/lib/forms-schema/index.ts, src/lib/forms-validation/index.ts, tests/forms-schema/forms-schema.test.ts
=> ON-44919 # Added CONCURRENT approval steps to SDK

package-lock.json
=> ON-45015 # update types

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema.test.ts
=> ON-45074 # `disableAutosave` to Form schema

package-lock.json, package.json
=> ON-45262 # Bumped @oneblink/storage

package-lock.json, package.json
=> ON-45352 # Bumped @oneblink/storage

package-lock.json, package.json
=> ON-45401 # Bumped @oneblink/storage

CHANGELOG.md, package-lock.json
=> ON-45508 # Added styles to FormsAppEnvironment

package-lock.json, package.json
=> ON-45721 # Bumped @oneblink/storage

package-lock.json, package.json
=> ON-45830 # Bumped @oneblink/storage

CHANGELOG.md, package-lock.json, package.json, src/lib/forms-schema/index.ts
=> ON-45969 # Added `isArchived` prop to Form

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/RepeatableSetElement.ts
=> ON-46251 # support layout property in RepeatableSetElement

tests/forms-schema/forms-schema.test.ts
=> ON-46371 # add jest tests for repeatable set layout

CHANGELOG.md, package-lock.json, package.json, src/lib/forms-schema/elements/SelectElement.ts, src/lib/forms-schema/index.ts, src/lib/forms-validation/validate-form-events.ts
=> ON-46691 # Added sharepoint form workflow to form validation

src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema-form-events.test.ts
=> ON-46794 # Added missing form workflow event type for sharepoint

src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema-form-events.test.ts
=> ON-46932 # Added PDF config to SHAREPOINT_STORE_FILES workflow event

package-lock.json, src/lib/forms-schema/index.ts, src/lib/forms-validation/common.ts, src/lib/forms-validation/index.ts, src/lib/forms-validation/validate-form-events.ts, tests/forms-schema/forms-schema-form-events.test.ts
=> ON-47007 # Fixed custom pdf mapping

src/lib/forms-schema/index.ts
=> ON-47083 # Added string array support to form element mappings

CHANGELOG.md, package-lock.json, package.json, src/lib/forms-schema/index.ts
=> ON-47530 # Added custom pdf read only validation

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema-form-events.test.ts
=> OB-2228 # Added civic rec workflow event validation

package-lock.json, package.json
=> OB-2345 # Bumped release cli

CHANGELOG.md, src/lib/forms-schema/elements/PointElement.ts
=> OB-2362 # Added `isDisplayingAddressInformation` to `pointAddress` form element

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts
=> OB-2373 # Added sharepointIntegrationEntraApplicationId property to form validation

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/PointElement.ts
=> AP-2551 # Added version to NSW Point address form element validation

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> ON-47883 # Enhance arcGISWebMap element schema with new properties

package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> ON-47898 #  Add additional widget props to `arcGISWebMap` element

CHANGELOG.md, package-lock.json, src/lib/forms-schema/element-schema.ts, src/lib/forms-schema/elements/PointCadastralParcelElement.ts, src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema.test.ts
=> AP-2646 # added pointCadastralParcel form element type

package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> ON-47906 # Change to `allowedDrawingTools`, add `graphicTypes`

package-lock.json, package.json
=> AP-2653 # Bumped @oneblink/sdk-core

src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> ON-48059 # Default arcgis home and address widgets to false in schema

package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> ON-48076 # Add `id` to `graphicTypes`

package-lock.json
=> MS-181 # Bump types

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/NumberElement.ts
=> AP-3351 # add validation for isCurrency on NumberElement

package-lock.json, package.json
=> AP-3357 # Bumped @oneblink/sdk-core

package-lock.json, package.json
=> AP-3384 # Bumped @oneblink/sdk-core

CHANGELOG.md, src/classes/Forms.ts, src/lib/one-blink-api.ts, tests/forms.test.ts
=> AP-3591 # Added generateBearerToken function to OneBlinkAPI class

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> MS-365 # Add `id` to `ArcGISWebMapElement.defaultValue.layers`

package-lock.json, package.json
=> MS-393 # Bumped @oneblink/sdk-core

CHANGELOG.md, src/lib/forms-schema/index.ts, tests/forms-schema/forms-schema.test.ts
=> MS-431 # Add `ELEMENT_VALUE:` to `emailSchema`

package-lock.json, package.json
=> MS-523 # Bump release cli and add --force flag

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> MS-456 # added `visible` to `ArcGISWebMapElement.defaultValue.layers`

CHANGELOG.md, src/lib/forms-schema/index.ts
=> ap-3892 # Added `footer` to form schema

package-lock.json, package.json
=> AP-3935 # Bumped @oneblink/storage

CHANGELOG.md, package-lock.json, package.json
=> MS-544 # Bump @oneblink/storage

CHANGELOG.md, src/lib/forms-schema/elements/FormElement.ts, tests/forms-schema/forms-schema.test.ts
=> MS-477 # Add `readOnly` to `FormElement`

CHANGELOG.md, package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> MS-577 # Add `measurementDimensionsEnabled` to `ArcGISWebMapElement`

package-lock.json, package.json
=> AP-4181 # Bumped @oneblink/storage

package-lock.json
=> AP-4194 # bump types

package-lock.json, src/lib/forms-schema/elements/ArcGISWebMapElement.ts
=> AP-4446 # update ArcGISWebMapElement validation

package-lock.json, package.json
=> AP-4489 # Bumped @oneblink/storage

CHANGELOG.md, package-lock.json, src/classes/Forms.ts
=>  AP-4581 # Added path to attachments

CHANGELOG.md, package-lock.json, src/classes/FormsApps.ts, tests/forms-apps.test.ts
=> MS-808 # Allow `emailAddress` to be optional

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts
=> AP-5020 # Added PAYMENT_DETAIL to form workflow validation

package-lock.json, package.json
=> AP-5042 # Bumped @oneblink/sdk-core

CHANGELOG.md, package-lock.json, src/lib/forms-schema/index.ts
=> AP-5172 # Added pdfConfigurations to email submission event validation

CHANGELOG.md, src/lib/forms-schema/index.ts
=> ap-5444 # Fixed missing prop in validation
